### ISSUE TITLE
Skull Heads without Skin?

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Shevchik/ProtocolSupport#12]
I don't know if this is a known issue, but, when someone places a Player Skull Head with a skin, only the player who placed it will see the skin, the rest of the players will see a Steve Head.

But, if someone equips the Player Skull Head, the others players can see the skin on the equiped player, but the issue still persists on placed Player Skull Heads.

Server Version: 1.8.3-R0.1-SNAPSHOT (compiled yesterday)
Client Version: 1.7.2

**Comment by Shevchik** [comment]
That's because placed skull skin is distributed through a tile entity update packet. Will probably fix it later.

**Comment by MrPowerGamerBR** [comment]
Then, after one day, you publish a version with the Skin Head fix!

You are awesome! :+1:
