### ISSUE TITLE
[1.5.2/1.6.X/1.7.X] Can't edit/write on different colored signs

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Shevchik/ProtocolSupport#13]
If a 1.7.2 client tries to write a birch/spruce/jungle/acacia/dark oak sign, the edit sign GUI is never displayed, and the sign is automatically placed on the ground.

The oak sign is unaffected.

**Comment by Tom-III** [comment]
The GUI packet for the sign is probably not sent

**Comment by Shevchik** [comment]
It is sent by the server anyway, so the reason is somewhere else.
There wan't a server->client open sign packet in earlier versions, client opened the gui on placement by himself.

**Comment by MrPowerGamerBR** [comment]
Tested again in the Dev Builds, now this issue doesn't exist anymore!

I will close the issue. Fixed in the lastest dev builds.
