### ISSUE TITLE
[1.5.2/1.6.4] When viewing a map item, the client crashes.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Shevchik/ProtocolSupport#14]
If you view a map in a 1.5.2 client, the client will crash.

The crash will also happen if you pick up a map and view it.

Client Crash (Map on a ItemFrame): http://pastebin.com/xaKNE3CC

Client Crash (when creating a map): http://pastebin.com/DiCtZh9K

This happens on the last devbuild of ProtocolSupport (Heads support), ~~but it didn't happen on the devbuild with the Map on 1.5.2, 1.6.4, 1.7.2 implemention~~

~~This commit *may* be that source of this problem, because builds before this commit shows the map correctly: 5c7dc43c3f9a76eb489fa9e0af8e509dc75d26ee~~

1.7.2 client is unaffected by this bug, and does show the map without crashing.

EDIT: No matter what ProtocolSupport build, the map will always crash the client.

**Comment by Shevchik** [comment]
Strange, it worked fine for me. Probably i missed the map color remap for it, so that's why i didn't find it at testing.

**Comment by MrPowerGamerBR** [comment]
@Shevchik yeah, for me , it did work when I tested on my local server (this was when you first published the build with the fix), but now it is not working for some reason.

It may be because of the map containing 1.7 blocks, because, when I first tested, it was on a forest biome, and now, when I tested, it was in a Server Spawn.

**Comment by Shevchik** [comment]
Try with 1.6.4, if it crashes too than it is totally because i forgot to remap some color.

**Comment by MrPowerGamerBR** [comment]
@Shevchik tested in 1.6.4, it does crash when seeing a map.

**Comment by Shevchik** [comment]
Should be fixed now, but i didn't test it.

**Comment by MrPowerGamerBR** [comment]
Tested and it is working correctly (at least on 1.5.2)! Thanks! :+1:
