### ISSUE TITLE
[1.5.2/Maybe 1.6.4, didn't test] Random Crash

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Shevchik/ProtocolSupport#17]
Crash Log: http://pastebin.com/fFHrg4Qr

I will try to find what block/entity is causing this crash.

**Comment by Shevchik** [comment]
Still have no idea what exactly cause this. I filter all the datawatcher so this shouldn't happen. How exactly did it occur? (That is related to active potion effects btw)

**Comment by MrPowerGamerBR** [comment]
@Shevchik it happens randomly, it "may" be due to a beacons\ (I was near a beacon when this did happen, but I think it wasn't activated with potion effects)

I will try to reproduce the error later :+1:

**Comment by MrPowerGamerBR** [comment]
Got it, the beacon has a Speed effect: http://prntscr.com/6x1n5r

**Comment by Shevchik** [comment]
Strange, doesn't cash for me.

**Comment by MrPowerGamerBR** [comment]
I would give, but it's my Server Spawn, and it would be very difficult to transfer it.

I will try to reproduce the problem in a local server, if I can't reproduce, I will transfer the map for you

**Comment by Shevchik** [comment]
Looks like i found the reason behind this random crashes. Try latest build.
