### ISSUE TITLE
[1.7/1.8] Problem with 1.7 clients animation

### ISSUE THREAD

**Issue by GmHtAf** [Shevchik/ProtocolSupport#19]
Hey,
So in my 1.8.3 spigot server, there is a problem with 1.7 clients animation (arm_animation), i don't know if it is spigot or protocolSupport :
A 1.8 client see a 1.7 client moving his arm normally, but just 4-5 times, and then nothing . The 1.7 continue to move arm, but 1.8 client see nothing about the 1.7, just the bloc break or other actions of 1.7 client .
However, a 1.7 client has no problem to see all animation of a 1.8 client.
So, protocol problem :x ?

**Comment by Shevchik** [comment]
>_< looks like i found the problem behind this issue

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by GmHtAf** [comment]
Yes it seem to work great now, thanks ^^ !
