### ISSUE TITLE
Dev. ProtocolSupport bug

### ISSUE THREAD

**Issue by fhntv24** [Shevchik/ProtocolSupport#20]
When server works for a few hours server stops accepting new players. Server thread does work, and all connection that was before works too. I'm using latest spigot build.
Plugin list:
UralClans, HideStream, PVPGunPlus, WorldEdit, NoCheatPlus, Fixer, DynPad, JoinCommands, Vault, CPFix, ScoreboardStats, PermissionsEx, KillerMoney, GodItem, RainbowArmour, WorldGuard, Stop127, ProtocolSupport, boosCooldowns, SiberianChatFilter, MineResetLite, AntiSwear, AutoMessage, AuthMe, Marriage, ChestCommands, DrugsFTW, ClearLag, EndlessOnline, NoFlyPvp, TrophyHeads, WGExtender, Essentials, ChatManager, EssentialsSpawn, ShoppingCartReloaded, LimitedWorldEdit.

Almost all plugins are latest version. WG and WE is 6.x build.

**Comment by fhntv24** [comment]
From logs:
[09:47:53 INFO]: ali12344 lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
[09:47:53 INFO]: 600600 lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
[09:47:53 INFO]: ChibiNeko195 lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe

A lot of ppl got kicked with Broken pipe reason, and now no one can connect.

**Comment by Shevchik** [comment]
Disable native-transport in minecraft server config. For unknown reason it doesn't work. Probably i'm missing something somewhere.

**Comment by fhntv24** [comment]
Could you add that to bukkit page ?

**Comment by fhntv24** [comment]
spigot page *

**Comment by Shevchik** [comment]
No, that bug only happens on some linux systems with very old libc versions. (CentOS 6, Ubuntu 12.10, Debian 6).

**Comment by fhntv24** [comment]
But i'm using Debian 7

**Comment by fhntv24** [comment]
Debian GNU/Linux 7.7

Linux *** #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64 GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=Debian
DISTRIB_RELEASE=7
DISTRIB_CODENAME=
DISTRIB_DESCRIPTION=

**Comment by Shevchik** [comment]
Debian 7 has older version of libc even than ubuntu 12.10, and native transport doesn't work on ubuntu 12.10 while it already works with ubuntu 13.10 (libc 2.19)

**Comment by fhntv24** [comment]
Thanks for info.
