### ISSUE TITLE
Nametags arent visible (1.5 - 1.7)

### ISSUE THREAD

**Issue by fhntv24** [Shevchik/ProtocolSupport#21]
Nametags on mobs arent visible for client version 1.5 - 1.7. 1.8 clients see them only when they hover on mobs, but 1.5 - 1.7 arent seeing them at all.

Also, arrow or item hack doesnt work with 1.5 - 1.7. Client just doesnt get nametags. Also if you rename mobs with nametag that will work, but re logining hides it again.

**Comment by fhntv24** [comment]
Also if you need test server for bungee protocol lib version - i can help you with that ( minigames )

**Comment by Shevchik** [comment]
Should be fixed now
