### ISSUE TITLE
[1.5.2] Received string length longer than maximum allowed (69/64)

### ISSUE THREAD

**Issue by kangarko** [Shevchik/ProtocolSupport#23]
On spawn, I am getting kicked with message:
Received string length longer than maximum allowed (69/64)

can this be caused by a sign text or a holograph?

**Comment by Shevchik** [comment]
IDK, probably item name actually. Need your map to debug.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by kangarko** [comment]
Thank you :)
