### ISSUE TITLE
Cannot see HolographicDisplays with 1.7.* client

### ISSUE THREAD

**Issue by jiongjionger** [Shevchik/ProtocolSupport#24]
Cannot see HolographicDisplays with 1.7.* client
Spigot: 1.8.3

**Comment by Shevchik** [comment]
Not a bug. Old clients don't support armorstands.

**Comment by jiongjionger** [comment]
I tried to fix the problem, but it didn't work.

at protocolsupport.protocol.transformer.v_1_7.remapper.java add:

replacementsLiving[30] = 100;
replacementsLiving[78] = 100;

and delete 

if (type == 78) { //skip armor stand
	return;
}

if (type == 30) { //skip armor stand
	return;
}

at protocolsupport.protocol.transformer.v_1_7.clientboundtransformer.PlayPacketTransformer.java

Why I can't see the horse(armor stands). Can you help me?

* Sorry for my poor English.

**Comment by Shevchik** [comment]
You forgot to remap datawatcher metadata, also you need a wither skull and correct position of horse to make hogramms work.

**Comment by Shevchik** [comment]
Also some plugin authors tend to spawn armorstand using SpawnObject packet, while they should be spawned using SpawnLiving packet.

**Comment by jiongjionger** [comment]
I keep trying to fix this problem. Thank you for your help!

**Comment by Shevchik** [comment]
You won't be able to solve this on ProtocolSupport side. You will have to track entity metadata and check it every packet, spawn two entities, store them somewhere, etc, etc... It will just a lot easier to rewrite hologramm plugin you use, to check client version using ProtocolSupportAPI and spawn old-style hologramms for them.
