### ISSUE TITLE
Possible bug, why is Level-Type not sent with packet Respawn (0x09) in 1.6?

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupport#25]
At package protocolsupport.protocol.transformer.v_1_6.clientboundtransformer;
line 93 is 0x07: { //PacketPlayOutRespawn
It sends out a packet with information byte,int,byte,byte,short however the Protocol Documentation says it should also send out the Level-Type string:
http://wiki.vg/index.php?title=Protocol&oldid=4899#Respawn_.280x09.29
Is this intended because the string is not used (or sent via other packets?) or is this a bug that has to be fixed?
Luckily adding "serializer.writeString(packetdata.readString(32767));" no quotes fixes this without any negative behavior

**Comment by Shevchik** [comment]
Well, looks like i forgot it somehow.
