### ISSUE TITLE
You spawn lower than normal in minecarts in 1.5.2

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupport#26]
When you enter Minecarts in 1.5.2 you are sort of inside the minecart instead of above it.
![Minecart glitch](http://i.imgur.com/3ixEaib.png)

This also applies to 1.5.1 and 1.5 (I've added support for those)
1.5 and 1.5.1 use the same protocol that 1.5.2 uses, the only thing that was changed is the protocol revision number so all that has to be done is add them to the ProtocolVersion.java and wherever else 1.5.2 is referenced add a 1.5.1 protocolversion

**Comment by Shevchik** [comment]
Well, don't have an idea why this happens, so i just decided to leave at as is. Too much changes in vehicle handling...

As for adding 1.5.1 support - it is pointless because you can't find out if your server was pinged by 1.5.2 or 1.5.1/1.5 client.

**Comment by Tom-III** [comment]
The ping does not work because the client does not send its version however that doesn't mean you can't join.  Also if 1.5.1 support is pointless we can take it down a notch
!(http://i.imgur.com/yNeGgRS.png)[1.4 yayyy!]

**Comment by Shevchik** [comment]
Yea you can join directly, but what is the point? Player won't be able to see that your server supports your version anyway.
I can actually easy go down straight to 1.3.2, but what's the point?
