### ISSUE TITLE
In 1.5.2 PacketPlayInEntityAction 0x13 actionId s are 1 too high (Can't sneak/run)

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupport#28]
In Minecraft 1.8 EntityAction is zero based because its a VarInt: http://wiki.vg/Protocol#Entity_Action
In Minecraft 1.5.2 EntityAction starts at 1 because its a byte: http://wiki.vg/index.php?title=Protocol&oldid=1039#Entity_Action_.280x13.29

This means that 1.5.2 players can not see other players sprint, stop sprinting, crouching or being in beds
I have fixed it by changing case 0x13: { //PacketPlayInEntityAction to
```java
			case 0x13: { //PacketPlayInEntityAction
				packet = getPacketById(0x0B);
				packetdata.writeVarInt(serializer.readInt());
				int actionId = 0;
				actionId = serializer.readByte();
				actionId = actionId - 1; // We subtract 1 because in 1.4.x 0x13 uses a byte and now its a VarInt
				packetdata.writeVarInt(actionId);
				packetdata.writeVarInt(0);
				break;
			}
```

**Comment by Shevchik** [comment]
Fixed, thanks.
