### ISSUE TITLE
Time outs with latest Spigot builds on 1.8.7.

### ISSUE THREAD

**Issue by CryMC** [Shevchik/ProtocolSupport#40]
I have no evidence to reproduce this other than the fact that whenever I add this plugin, i notice a high amount of time outs and disconnects every 5 minutes or so at random, along with increased ping +100ms~ ... 

I have been updating consistently whenever I see a new commit, but this still seems to happen.
Are you aware of this issue? I was not able to reproduce it myself alone, seems to only happen when there are 50+ players on.

How do I know this plugin causes it? Removing it solved the time outs. 
I have connection throttle at -1 and late bind set to false. Is there anything i'm missing?

**Comment by Shevchik** [comment]
Try disabling native in server.properties.
ProtocolSupport had some problems with epoll channel, and i'm still not sure if it works now.

**Comment by CryMC** [comment]
Okay, also is this safe to use with bungee?

**Comment by sgdc3** [comment]
Yes, but you need to add this plugin to bungeecord: https://www.spigotmc.org/resources/protocolsupportbungee.8733/

**Comment by CryMC** [comment]
Awesome, thank you.

**Comment by CryMC** [comment]
Im seeing this on Bungee (with ps plugin) and a test server using Spigot 1.8.7 http://crymc.co/dBY2 . I connected with a 1.7.10 client and ran around, then kicked.

Console prints: java.lang.NegativeArraySizeException

**Comment by Shevchik** [comment]
Enable debug using ps debug command and try again.

**Comment by CryMC** [comment]
[12:21:44 INFO]: Enabled debug
[12:21:52 ERROR]: java.lang.NegativeArraySizeException

The kick happens and same error gets printed but I don't see any debug info?

**Comment by Shevchik** [comment]
Well, sometimes built-in minecraft server debug is shit. I thought it will print the stacktrace of java.lang.NegativeArraySizeException.
Okay, can you give me your server ip? I will try to join with debug client and see whats wrong.

**Comment by CryMC** [comment]
I use local host for testing this as I have not had a good experience with putting it in my live server.
Do you have Skype and i could send you my ip when im online?

**Comment by Shevchik** [comment]
The negative array size exception should fe fixed now

**Comment by CryMC** [comment]
Will test shortly.
