### ISSUE TITLE
1.5.2 and 1.6.X user opposite Time

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#43]
what is mean. 1.7.X and 1.8.X User set time set morning. Then 1.5.2 and 1.6.X User see the night. 
1.5.2 and 1.6.X User are opposite time to 1.7.X 1.8.X user (but No console Error)

i use 1.8.8 Spigot and 8/1 Protocolsupport Build

**Comment by Shevchik** [comment]
I will look into it

**Comment by MrPowerGamerBR** [comment]
I tested with the Essentials /time commands, this issue didn't happen to me on a 1.5.2 client.

Used /time night, the time is night on the 1.5.2 client.

Used /time day, the time is day on the 1.5.2 client.
