### ISSUE TITLE
[CRITICAL] ProtocolSupportBungee and ProtocolSupport have the same command!

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupport#51]
If you run protocolsupportbungee and protocolsupport you can't use protocolsupport's /ps since protocolsupportbungee takes priority because bungeecord commands always are interpreted first.

**Comment by Shevchik** [comment]
/protocolsupport:ps
Bungee doesn't have plugin name aliasing so this works 100%
