### ISSUE TITLE
Would it be possible to add upwards compatibility?

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupport#53]
Considering Minecraft Snapshots have been released how possible is it to add upwards compatibility to ProtocolSupport?  Kinda like 1.7 protocol hack spigot
Ill start playing around with it like I did the 1.4 connection.

**Comment by Shevchik** [comment]
It is, but i won't do it. There is a Carbon project for it.

**Comment by Tom-III** [comment]
However the carbon project adds the new blocks, dual wielding and such which we don't want, we just want people with their client set to "Use latest version" to be able to connect to our server.
