### ISSUE TITLE
Minecraft client Crash when wither spawn-[spigot 1.8.8]-[minecraft 1.7.10]

### ISSUE THREAD

**Issue by collller** [Shevchik/ProtocolSupport#55]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 15-9-19 AM9:52
Description: Ticking entity

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte
	at te.a(SourceFile:83)
	at zp.f(SourceFile:103)
	at zp.e(SourceFile:33)
	at ze.h(SourceFile:165)
	at ahb.a(SourceFile:1368)
	at ahb.g(SourceFile:1346)
	at ahb.h(SourceFile:1253)
	at bao.p(SourceFile:1552)
	at bao.ak(SourceFile:774)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:120)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at te.a(SourceFile:83)
	at zp.f(SourceFile:103)
	at zp.e(SourceFile:33)
	at ze.h(SourceFile:165)
	at ahb.a(SourceFile:1368)
	at ahb.g(SourceFile:1346)

-- Entity being ticked --
Details:
	Entity Type: WitherSkull (zp)
	Entity ID: 1318
	Entity Name: entity.WitherSkull.name
	Entity's Exact location: 205.78, 66.19, 191.50
	Entity's Block location: World: (205,66,191), Chunk: (at 13,4,15 in 12,11; contains blocks 192,0,176 to 207,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at ahb.h(SourceFile:1253)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bjk['YASJUN'/898, l='MpServer', x=203.83, y=65.62, z=192.86]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (200,64,188), Chunk: (at 8,4,12 in 12,11; contains blocks 192,0,176 to 207,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 379 game time, 379 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 37 total; [bjk['YASJUN'/898, l='MpServer', x=203.83, y=65.62, z=192.86], xk['item.tile.torch'/7, l='MpServer', x=176.66, y=25.13, z=193.69], xk['item.tile.torch'/9, l='MpServer', x=178.44, y=24.13, z=212.88], xz['Creeper'/1298, l='MpServer', x=192.50, y=19.00, z=211.50], xk['item.tile.torch'/20, l='MpServer', x=197.13, y=27.99, z=204.33], xm['entity.MinecartChest.name'/21, l='MpServer', x=198.50, y=19.06, z=211.50], xm['entity.MinecartChest.name'/23, l='MpServer', x=184.50, y=24.06, z=240.50], xk['item.tile.torch'/27, l='MpServer', x=202.53, y=24.13, z=175.03], xk['item.tile.rail'/32, l='MpServer', x=192.09, y=24.13, z=194.91], xk['item.tile.rail'/37, l='MpServer', x=198.84, y=28.13, z=204.59], xc['Wither'/1317, l='MpServer', x=204.50, y=64.00, z=191.50], xk['item.tile.torch'/38, l='MpServer', x=207.88, y=24.13, z=213.72], zp['entity.WitherSkull.name'/1318, l='MpServer', x=205.78, y=66.19, z=191.50], xk['item.tile.torch'/39, l='MpServer', x=204.28, y=28.13, z=225.09], zp['entity.WitherSkull.name'/1319, l='MpServer', x=203.19, y=66.19, z=191.50], xm['entity.MinecartChest.name'/40, l='MpServer', x=204.50, y=28.06, z=222.50], xk['item.tile.torch'/41, l='MpServer', x=206.94, y=19.13, z=223.53], yn['Spider'/1119, l='MpServer', x=167.50, y=25.00, z=212.50], yq['Zombie'/1131, l='MpServer', x=220.50, y=34.00, z=228.50], yq['Zombie'/1136, l='MpServer', x=212.50, y=34.00, z=193.88], xk['item.tile.gravel'/656, l='MpServer', x=178.34, y=25.13, z=185.13], yl['Skeleton'/1181, l='MpServer', x=252.50, y=41.00, z=231.50], xz['Creeper'/926, l='MpServer', x=218.50, y=34.00, z=228.50], xz['Creeper'/927, l='MpServer', x=217.28, y=34.00, z=225.53], xz['Creeper'/928, l='MpServer', x=219.15, y=29.07, z=227.45], xz['Creeper'/930, l='MpServer', x=239.50, y=13.00, z=240.50], xz['Creeper'/1230, l='MpServer', x=183.50, y=25.00, z=186.50], yn['Spider'/1232, l='MpServer', x=180.50, y=25.00, z=185.50], yq['Zombie'/1240, l='MpServer', x=199.50, y=24.00, z=188.03], yq['Zombie'/1241, l='MpServer', x=199.47, y=24.00, z=189.13], yl['Skeleton'/1242, l='MpServer', x=209.50, y=24.00, z=190.50], yl['Skeleton'/1244, l='MpServer', x=193.50, y=20.00, z=217.50], yl['Skeleton'/1245, l='MpServer', x=194.50, y=20.00, z=218.50], xz['Creeper'/1249, l='MpServer', x=182.34, y=25.00, z=195.03], yl['Skeleton'/1258, l='MpServer', x=198.50, y=24.00, z=218.50], yl['Skeleton'/1259, l='MpServer', x=198.50, y=24.00, z=217.50], yl['Skeleton'/1260, l='MpServer', x=197.50, y=24.00, z=215.50]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bjf.a(SourceFile:289)
	at bao.b(SourceFile:1972)
	at bao.f(SourceFile:737)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:120)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 56709656 bytes (54 MB) / 200773632 bytes (191 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx512m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.7.10_NO_MOD
	LWJGL: 2.9.1
	OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.54, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by swan201** [comment]
I think this issue is very simuler https://github.com/Shevchik/ProtocolSupport/issues/46 this issue

**Comment by Shevchik** [comment]
No, this issue occurs because of wrong remapping table for wither skull.

**Comment by Shevchik** [comment]
Should be fixed now, try again.

**Comment by swan201** [comment]
close this issue :D
