### ISSUE TITLE
Mobile chat apps are not compatible with servers running protocolsupport

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupport#57]
For some reason Minechat and other variants of mobile chat apps don't work on servers with ProtocolSupport or ProtocolSupportBungee, it keeps saying "Pinging..." and fails to connect to the server.

**Comment by Shevchik** [comment]
Obviously it is a problem on their side, vanilla works.

**Comment by swan201** [comment]
Yes Some APP cant ping to useing Protocolsupport. But Hyper Chat App can connect to Protocolsupport useing server
