### ISSUE TITLE
1.7 clients being allowed to see holograms. 

### ISSUE THREAD

**Issue by Eternalrealms** [Shevchik/ProtocolSupport#60]
Is it possible to allow 1.7 clients to see holograms? I know this was done with the protocol hack and with this plugin " https://www.spigotmc.org/resources/holographic-displays-patch.1039/ " the plugin currently does not work for 1.8.8. Are you able to add support for this?

**Comment by Shevchik** [comment]
Yes it is possible, but i'm nog going to do this.
