### ISSUE TITLE
Client crash. 

### ISSUE THREAD

**Issue by Eternalrealms** [Shevchik/ProtocolSupport#61]
Take a pair of depth strider boots, when you're on 1.7 it doesn't SAY they have depth strider but when you put them in an anvil it crashes their client.

It says this on their client. https://gyazo.com/2b92fdc8d9ee177e0d992ebc152130d8

Pastebin of error: http://pastebin.com/WSQ6mDfm

**Comment by MrPowerGamerBR** [comment]
Can confirm, also crashes 1.5.2.

Here is a log from the 1.5.2 client: http://pastebin.com/eyj4NYCB

**Comment by MrPowerGamerBR** [comment]
A very simple fix would be changing the PacketDataSerializer class to verify the player version and removing the affected enchant and then sending the item without the enchant.

Like this:
org.bukkit.inventory.ItemStack is = CraftItemStack.asBukkitCopy(itemstack);
		
    /*
    * TODO: Need to verify the player's version before stripping the enchant.
    */
    if (is.containsEnchantment(Enchantment.DEPTH_STRIDER)) {
        is.removeEnchantment(Enchantment.DEPTH_STRIDER);
    }
    itemstack = CraftItemStack.asNMSCopy(is);
This works, however it will remove the enchant to every client, not only to 1.5/1.6/1.7 clients, and no player argument is passed to the "a" function (however, you can get the version using getVersion()), so it will be a very easy fix.

To added bonus, you can edit the item lore to add the Depth Strider enchant, so people without 1.8 could at least see the enchant on the item.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MrPowerGamerBR** [comment]
@Shevchik I didn't test, but after doing a quick look on the modified code, it doesn't verify for the fishing enchantments that didn't exist on 1.5.2 and 1.6.4, those enchants (Enchantment.LURE and Enchantment.LUCK) also make the client crash.
