### ISSUE TITLE
Player shifting

### ISSUE THREAD

**Issue by dobrac** [Shevchik/ProtocolSupport#62]
When you press shift it doesn't do anything, but on another server with same settings it showed something, but when I teleported to player while he was shifting and the player after my teleport stopped shifting, he stayed in shifted position and he can sprint with this possition.

Spigot version: 1.8.8
ProtocolSupport version: 4.20

Client version: 1.7

**Comment by MrPowerGamerBR** [comment]
Can also confirm, for another player I was always sneaking, however I wasn't sneaking.

**Comment by Shevchik** [comment]
Should be fixed now
