### ISSUE TITLE
Fire particles

### ISSUE THREAD

**Issue by dobrac** [Shevchik/ProtocolSupport#63]
When you are burning (after you leave fire) you don't see any effect (like when you were in the fire).

Spigot version: 1.8.8
ProtocolSupport version: 4.20

Client version: 1.7

**Comment by MrPowerGamerBR** [comment]
Can confirm, this happens ONLY with the 1.7.2 client (1.5.2 client is unaffected).

The fire damage persists, however the fire animation does not appear.

**Comment by Shevchik** [comment]
Probably related to sneaking problem, something is wrong with metadata resending, because server always gets the state right.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MrPowerGamerBR** [comment]
Fixed in the lastest Dev Build.
![2015-10-17_13 46 11](https://cloud.githubusercontent.com/assets/9496359/10560056/7abb53d6-74d5-11e5-80b8-a10aede3b38e.png)
